#!/bin/bash

# Copyright (c) 2001 Alcove - http://www.alcove.com/
# Please distribute under the terms of the GNU GPL, version 2

# Author: Yann Dirson <yann.dirson@fr.alcove.com>
# $Id: zxpdf,v 1.1 2001/09/28 10:23:35 ydirson Exp $

set -e

flags=""
while [ "$#" -gt "0" ]; do
    case "$1" in
    -z|-g|-geometry|-remote|-rgb|-papercolor|-eucjp|-t1lib|-ps|-paperw|-paperh)
	flags="$flags $1 $2"; shift ;;
    -title) title="$2"; shift ;;
    -*) flags="$flags $1" ;;
    *.[pP][Dd][Ff]) 
        cat=""
        test -f "$1"     && cat="cat"   && file="$1"     || true
        test -f "$1.Z"   && cat="zcat"  && file="$1.Z"   || true
        test -f "$1.gz"  && cat="zcat"  && file="$1.gz"  || true
        test -f "$1.bz2" && cat="bzcat" && file="$1.bz2" || true
        test -f "$1.xz"  && cat="xzcat" && file="$1.xz"  || true
        test "$cat" = "" && (echo >&2 "Error: file not found: '$1'" && false)
        shift && pages="$@" && break ;;
    *.gz|*.Z)
        test -f "$1" && cat="zcat" && file="$1" && shift && pages="$@" && break ||
            (echo >&2 "Error: file not found: '$1'" && false) ;;
    *.bz2)
        test -f "$1" && cat="bzcat" && file="$1" && shift && pages="$@" && break ||
            (echo >&2 "Error: file not found: '$1'" && false) ;;
    *.xz)
        test -f "$1" && cat="xzcat" && file="$1" && shift && pages="$@" && break ||
            (echo >&2 "Error: file not found: '$1'" && false) ;;
    *)
        echo >&2 "ERROR: unknown suffix in file: '$1'" && false ;;
    esac
    shift
done

test "$title" = "" && title="$file" || true
tmp=$(tempfile -p "$(basename "$file")" -s .pdf)
$cat "$file" > "$tmp"
xpdf -title $title $flags "$tmp" $pages || true
rm -f "$tmp"
