#!/bin/sh
# Copyright (c) 2001 Alcove (Yann Dirson <yann.dirson@fr.alcove.com>) - http://www.alcove.com/
# Copyright (C) 2011 Michael Gilbert <michael.s.gilbert@gmail.com>
# Copyright (C) 2011 Osamu Aoki <osamu@debian.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

file=""
many=""
pages=""
cmd="xpdf.real"
while [ "$#" -gt "0" ]; do
    case "$1" in
    -z|-g|-geometry|-remote|-rgb|-papercolor|-eucjp|-t1lib|-ps|-paperw|-paperh|-upw)
	cmd="$cmd $1 '$2'" && shift ;;
    -title)
        title="$2" && shift ;;
    -m)
        shift
        while [ "$#" -gt "0" ]; do
            case "$1" in
                -*) break ;;
                *) many=$(printf "%s\n%s" "$1" "$many") ;;
            esac
            shift
        done
        break ;;
    -*)
        cmd="$cmd $1" ;;
    *)
        test -f "$1" && file="$1" && shift && pages="$@" && break ||
            ( echo "error: \"$1\" file not found" && false ) ;;
    esac
    shift
done

test "$title" != "" || title="Xpdf: $file"
if [ "$many" != "" ]; then
    printf "%s" "$many" | while read -r file; do
        test ! -f "$file" || $0 "$file" &
    done
elif [ "$file" = "" ]; then
    $cmd -title "$title"
else
    tmp=$(tempfile -s .pdf)
    trap "rm -f \"$tmp\"" EXIT HUP INT QUIT TERM 
    case "$file" in
        *.gz|*.Z)  zcat "$file" > "$tmp" ;;
        *.xz)     xzcat "$file" > "$tmp" ;;
        *.bz2)    bzcat "$file" > "$tmp" ;;
        *) tmp="$file" ;;
    esac
    $cmd -title "$title" "$tmp" $pages || true
fi
