#!/bin/bash
# Copyright (c) 2001 Alcove (Yann Dirson <yann.dirson@fr.alcove.com>) - http://www.alcove.com/
# Copyright (C) 2011 Michael Gilbert <michael.s.gilbert@gmail.com>
# Copyright (C) 2011 Osamu Aoki <osamu@debian.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

cat=""
file=""
pages=""
cmd="xpdf.real"
while [ "$#" -gt "0" ]; do
    case "$1" in
    -z|-g|-geometry|-remote|-rgb|-papercolor|-eucjp|-t1lib|-ps|-paperw|-paperh)
	cmd="$cmd $1 $2"; shift ;;
    -title)
        title="$2" ;;
    -m)
        shift
        while [ "$#" != "0" ]; do
            xpdf "$1" &
            shift
        done ;;
    -*) cmd="$cmd $1" ;;
    *.[pP][Dd][Ff])
        test "$title" != "" || title="$1"
        test -f "$1"     && cat="cat"   && file="$1"     || true
        test -f "$1.Z"   && cat="zcat"  && file="$1.Z"   || true
        test -f "$1.gz"  && cat="zcat"  && file="$1.gz"  || true
        test -f "$1.bz2" && cat="bzcat" && file="$1.bz2" || true
        test -f "$1.xz"  && cat="xzcat" && file="$1.xz"  || true
        test "$cat" = "" && (echo >&2 "Error: file not found: '$1'" && false)
        shift && pages="$@" && break ;;
    *.gz|*.Z)
        test -f "$1" && cat="zcat" && title="$1" && file="$1" && shift && pages="$@" && break ||
            (echo >&2 "Error: file not found: '$1'" && false) ;;
    *.bz2)
        test -f "$1" && cat="bzcat" && title="$1" && file="$1" && shift && pages="$@" && break ||
            (echo >&2 "Error: file not found: '$1'" && false) ;;
    *.xz)
        test -f "$1" && cat="xzcat" && title="$1" && file="$1" && shift && pages="$@" && break ||
            (echo >&2 "Error: file not found: '$1'" && false) ;;
    *)
        echo >&2 "ERROR: unknown suffix in file: '$1'" && false ;;
    esac
    shift
done

if [ "$file" = "" ] || [ "$cat" = "cat" ]; then
    eval $cmd $file $pages
else
    tmp=$(tempfile -p "$(basename "$file")" -s .pdf)
    test "$cat" = "" || $cat "$file" > "$tmp"
    trap "rm -f \"$tmp\"" EXIT SIGHUP SIGINT SIGTERM 
    eval $cmd -title \'$title\' $tmp $pages || true
fi
